//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CncConvProg.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkDialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkDialogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CncConvProg.View.Properties.WorkDialogResources", typeof(WorkDialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bore Diameter.
        /// </summary>
        public static string boreDiameter {
            get {
                return ResourceManager.GetString("boreDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drill Diameter .
        /// </summary>
        public static string drillDiameter {
            get {
                return ResourceManager.GetString("drillDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bore Depth.
        /// </summary>
        public static string zBoreDepth {
            get {
                return ResourceManager.GetString("zBoreDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterbore Depth.
        /// </summary>
        public static string zCounterboreDepth {
            get {
                return ResourceManager.GetString("zCounterboreDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth Z.
        /// </summary>
        public static string zDepth {
            get {
                return ResourceManager.GetString("zDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drill Depth.
        /// </summary>
        public static string zDrillDepth {
            get {
                return ResourceManager.GetString("zDrillDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reamer Depth.
        /// </summary>
        public static string zReamerDepth {
            get {
                return ResourceManager.GetString("zReamerDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Z.
        /// </summary>
        public static string zSecure {
            get {
                return ResourceManager.GetString("zSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Z.
        /// </summary>
        public static string zStart {
            get {
                return ResourceManager.GetString("zStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap Depth.
        /// </summary>
        public static string zTapDepth {
            get {
                return ResourceManager.GetString("zTapDepth", resourceCulture);
            }
        }
    }
}
