//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MecPrev.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EditWorkRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditWorkRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MecPrev.Resources.EditWorkRes", typeof(EditWorkRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Arc.
        /// </summary>
        public static string AddArc {
            get {
                return ResourceManager.GetString("AddArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Line.
        /// </summary>
        public static string AddLine {
            get {
                return ResourceManager.GetString("AddLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AlternateArc.
        /// </summary>
        public static string AlternateArc {
            get {
                return ResourceManager.GetString("AlternateArc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle Direction.
        /// </summary>
        public static string AngleDirection {
            get {
                return ResourceManager.GetString("AngleDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arc.
        /// </summary>
        public static string Arc {
            get {
                return ResourceManager.GetString("Arc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Tool.
        /// </summary>
        public static string AutoTool {
            get {
                return ResourceManager.GetString("AutoTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bore Diameter.
        /// </summary>
        public static string boreDiameter {
            get {
                return ResourceManager.GetString("boreDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Point.
        /// </summary>
        public static string btnAddPoint {
            get {
                return ResourceManager.GetString("btnAddPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Rotation X.
        /// </summary>
        public static string CenterRotationX {
            get {
                return ResourceManager.GetString("CenterRotationX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Rotation Y.
        /// </summary>
        public static string CenterRotationY {
            get {
                return ResourceManager.GetString("CenterRotationY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center X.
        /// </summary>
        public static string CenterX {
            get {
                return ResourceManager.GetString("CenterX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Y.
        /// </summary>
        public static string CenterY {
            get {
                return ResourceManager.GetString("CenterY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamfer.
        /// </summary>
        public static string Chamfer {
            get {
                return ResourceManager.GetString("Chamfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamfering.
        /// </summary>
        public static string Chamfering {
            get {
                return ResourceManager.GetString("Chamfering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circumscribed.
        /// </summary>
        public static string Circumscribed {
            get {
                return ResourceManager.GetString("Circumscribed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate Radius Angle.
        /// </summary>
        public static string CoordinateRadiusAngle {
            get {
                return ResourceManager.GetString("CoordinateRadiusAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coordinate XY.
        /// </summary>
        public static string CoordinateXY {
            get {
                return ResourceManager.GetString("CoordinateXY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count X.
        /// </summary>
        public static string CountX {
            get {
                return ResourceManager.GetString("CountX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Y.
        /// </summary>
        public static string CountY {
            get {
                return ResourceManager.GetString("CountY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Tool.
        /// </summary>
        public static string CreateNewTool {
            get {
                return ResourceManager.GetString("CreateNewTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Diameter.
        /// </summary>
        public static string DiameterMax {
            get {
                return ResourceManager.GetString("DiameterMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterbore Diameter.
        /// </summary>
        public static string DiametroLamatura {
            get {
                return ResourceManager.GetString("DiametroLamatura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction.
        /// </summary>
        public static string Direction {
            get {
                return ResourceManager.GetString("Direction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drill Diameter .
        /// </summary>
        public static string drillDiameter {
            get {
                return ResourceManager.GetString("drillDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D-Slot.
        /// </summary>
        public static string DSlot {
            get {
                return ResourceManager.GetString("DSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Angle.
        /// </summary>
        public static string EndAngle {
            get {
                return ResourceManager.GetString("EndAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Diameter.
        /// </summary>
        public static string EndDiameter {
            get {
                return ResourceManager.GetString("EndDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Radius.
        /// </summary>
        public static string EndRadius {
            get {
                return ResourceManager.GetString("EndRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing.
        /// </summary>
        public static string Finishing {
            get {
                return ResourceManager.GetString("Finishing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Angle.
        /// </summary>
        public static string FirstAngle {
            get {
                return ResourceManager.GetString("FirstAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Point X.
        /// </summary>
        public static string InitalPointX {
            get {
                return ResourceManager.GetString("InitalPointX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Point Y.
        /// </summary>
        public static string InitialPointY {
            get {
                return ResourceManager.GetString("InitialPointY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside.
        /// </summary>
        public static string Inside {
            get {
                return ResourceManager.GetString("Inside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Instance.
        /// </summary>
        public static string InstanceCount {
            get {
                return ResourceManager.GetString("InstanceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lathe 2 Axis Phase.
        /// </summary>
        public static string Lathe2AxPhase {
            get {
                return ResourceManager.GetString("Lathe2AxPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lathe 3 Axis Phase.
        /// </summary>
        public static string Lathe3AxPhase {
            get {
                return ResourceManager.GetString("Lathe3AxPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material To Remove.
        /// </summary>
        public static string MaterialToRemove {
            get {
                return ResourceManager.GetString("MaterialToRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Mill Phase.
        /// </summary>
        public static string MillPhase {
            get {
                return ResourceManager.GetString("MillPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count X.
        /// </summary>
        public static string NumberCountX {
            get {
                return ResourceManager.GetString("NumberCountX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count Y.
        /// </summary>
        public static string NumberCountY {
            get {
                return ResourceManager.GetString("NumberCountY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Passate.
        /// </summary>
        public static string NumeroPassate {
            get {
                return ResourceManager.GetString("NumeroPassate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Abilited.
        /// </summary>
        public static string OperationAb {
            get {
                return ResourceManager.GetString("OperationAb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside.
        /// </summary>
        public static string Outside {
            get {
                return ResourceManager.GetString("Outside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override Parameter.
        /// </summary>
        public static string OverwriteParameter {
            get {
                return ResourceManager.GetString("OverwriteParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PatternParameter.
        /// </summary>
        public static string PatternParameter {
            get {
                return ResourceManager.GetString("PatternParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pattern Selection.
        /// </summary>
        public static string PatternSelection {
            get {
                return ResourceManager.GetString("PatternSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch.
        /// </summary>
        public static string Pitch {
            get {
                return ResourceManager.GetString("Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Editor.
        /// </summary>
        public static string ProfileEditor {
            get {
                return ResourceManager.GetString("ProfileEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Point Pos.
        /// </summary>
        public static string RefPointPos {
            get {
                return ResourceManager.GetString("RefPointPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Point X.
        /// </summary>
        public static string RefPointX {
            get {
                return ResourceManager.GetString("RefPointX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Point Y.
        /// </summary>
        public static string RefPointY {
            get {
                return ResourceManager.GetString("RefPointY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular Polygon.
        /// </summary>
        public static string RegularPolygon {
            get {
                return ResourceManager.GetString("RegularPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation Abilited.
        /// </summary>
        public static string RotationAb {
            get {
                return ResourceManager.GetString("RotationAb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roughing.
        /// </summary>
        public static string Roughing {
            get {
                return ResourceManager.GetString("Roughing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salva.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Different Tool.
        /// </summary>
        public static string SelectTool {
            get {
                return ResourceManager.GetString("SelectTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side Number.
        /// </summary>
        public static string SideNumber {
            get {
                return ResourceManager.GetString("SideNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        public static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Diameter.
        /// </summary>
        public static string StartDiameter {
            get {
                return ResourceManager.GetString("StartDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Z.
        /// </summary>
        public static string StartZ {
            get {
                return ResourceManager.GetString("StartZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        public static string Thread {
            get {
                return ResourceManager.GetString("Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Type.
        /// </summary>
        public static string ThreadType {
            get {
                return ResourceManager.GetString("ThreadType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Detail.
        /// </summary>
        public static string ToolDetailGroup {
            get {
                return ResourceManager.GetString("ToolDetailGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Parameter.
        /// </summary>
        public static string ToolParameter {
            get {
                return ResourceManager.GetString("ToolParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Position.
        /// </summary>
        public static string ToolPositon {
            get {
                return ResourceManager.GetString("ToolPositon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Wear.
        /// </summary>
        public static string ToolWear {
            get {
                return ResourceManager.GetString("ToolWear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translate Abilited.
        /// </summary>
        public static string TranslateAb {
            get {
                return ResourceManager.GetString("TranslateAb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Defined.
        /// </summary>
        public static string WorkDefined {
            get {
                return ResourceManager.GetString("WorkDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Not Defined.
        /// </summary>
        public static string WorkNotDefined {
            get {
                return ResourceManager.GetString("WorkNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bore Depth.
        /// </summary>
        public static string zBoreDepth {
            get {
                return ResourceManager.GetString("zBoreDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterbore Depth.
        /// </summary>
        public static string zCounterboreDepth {
            get {
                return ResourceManager.GetString("zCounterboreDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth Z.
        /// </summary>
        public static string zDepth {
            get {
                return ResourceManager.GetString("zDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drill Depth.
        /// </summary>
        public static string zDrillDepth {
            get {
                return ResourceManager.GetString("zDrillDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Distance X.
        /// </summary>
        public static string ZeroDistanceX {
            get {
                return ResourceManager.GetString("ZeroDistanceX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Distance Y.
        /// </summary>
        public static string ZeroDistanceY {
            get {
                return ResourceManager.GetString("ZeroDistanceY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZeroPoint.
        /// </summary>
        public static string ZeroPoint {
            get {
                return ResourceManager.GetString("ZeroPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reamer Depth.
        /// </summary>
        public static string zReamerDepth {
            get {
                return ResourceManager.GetString("zReamerDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Z.
        /// </summary>
        public static string zSecure {
            get {
                return ResourceManager.GetString("zSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Z.
        /// </summary>
        public static string zStart {
            get {
                return ResourceManager.GetString("zStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap Depth.
        /// </summary>
        public static string zTapDepth {
            get {
                return ResourceManager.GetString("zTapDepth", resourceCulture);
            }
        }
    }
}
