//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MecPrev.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GuiRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GuiRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MecPrev.Resources.GuiRes", typeof(GuiRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Cost.
        /// </summary>
        public static string AddCost {
            get {
                return ResourceManager.GetString("AddCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add _Machine.
        /// </summary>
        public static string AddMachine {
            get {
                return ResourceManager.GetString("AddMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bore.
        /// </summary>
        public static string Bore {
            get {
                return ResourceManager.GetString("Bore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boring.
        /// </summary>
        public static string Boring {
            get {
                return ResourceManager.GetString("Boring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Inche Thread.
        /// </summary>
        public static string btnAddInchThread {
            get {
                return ResourceManager.GetString("btnAddInchThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Material.
        /// </summary>
        public static string btnAddMaterial {
            get {
                return ResourceManager.GetString("btnAddMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Metric Thread.
        /// </summary>
        public static string btnAddMetricThread {
            get {
                return ResourceManager.GetString("btnAddMetricThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Price.
        /// </summary>
        public static string btnAddPrice {
            get {
                return ResourceManager.GetString("btnAddPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Table Row.
        /// </summary>
        public static string btnAddTableRow {
            get {
                return ResourceManager.GetString("btnAddTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Tool.
        /// </summary>
        public static string btnAddTool {
            get {
                return ResourceManager.GetString("btnAddTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        public static string btnCalculate {
            get {
                return ResourceManager.GetString("btnCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del Material.
        /// </summary>
        public static string btnDelMateriale {
            get {
                return ResourceManager.GetString("btnDelMateriale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del Price.
        /// </summary>
        public static string btnDelPrice {
            get {
                return ResourceManager.GetString("btnDelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Drill.
        /// </summary>
        public static string CenterDrill {
            get {
                return ResourceManager.GetString("CenterDrill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chamfer.
        /// </summary>
        public static string Chamfer {
            get {
                return ResourceManager.GetString("Chamfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Tool Time : [sec].
        /// </summary>
        public static string ChangeToolTime {
            get {
                return ResourceManager.GetString("ChangeToolTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        public static string Circle {
            get {
                return ResourceManager.GetString("Circle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contour.
        /// </summary>
        public static string ContourOp {
            get {
                return ResourceManager.GetString("ContourOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Cost.
        /// </summary>
        public static string CostiAggiuntiviDlg {
            get {
                return ResourceManager.GetString("CostiAggiuntiviDlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterbore.
        /// </summary>
        public static string Counterbore {
            get {
                return ResourceManager.GetString("Counterbore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counterboring.
        /// </summary>
        public static string Counterboring {
            get {
                return ResourceManager.GetString("Counterboring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CutDepth.
        /// </summary>
        public static string CutDepth {
            get {
                return ResourceManager.GetString("CutDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Parameter.
        /// </summary>
        public static string CutParameter {
            get {
                return ResourceManager.GetString("CutParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Speed.
        /// </summary>
        public static string CutSpeed {
            get {
                return ResourceManager.GetString("CutSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Time.
        /// </summary>
        public static string DefaultTimeGroup {
            get {
                return ResourceManager.GetString("DefaultTimeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Measure Unit.
        /// </summary>
        public static string DefaultUnit {
            get {
                return ResourceManager.GetString("DefaultUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined Price.
        /// </summary>
        public static string DefinedPrice {
            get {
                return ResourceManager.GetString("DefinedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Detail.
        /// </summary>
        public static string DettagliFase {
            get {
                return ResourceManager.GetString("DettagliFase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string Diameter {
            get {
                return ResourceManager.GetString("Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machines Dialog.
        /// </summary>
        public static string dlgMachine {
            get {
                return ResourceManager.GetString("dlgMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string dlgMaterial {
            get {
                return ResourceManager.GetString("dlgMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Detail.
        /// </summary>
        public static string DlgPhaseDetail {
            get {
                return ResourceManager.GetString("DlgPhaseDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SelectionUnit.
        /// </summary>
        public static string dlgSelectionUnit {
            get {
                return ResourceManager.GetString("dlgSelectionUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Table.
        /// </summary>
        public static string dlgTabellaFilettature {
            get {
                return ResourceManager.GetString("dlgTabellaFilettature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools Dialog.
        /// </summary>
        public static string dlgToolWindow {
            get {
                return ResourceManager.GetString("dlgToolWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drill.
        /// </summary>
        public static string Drill {
            get {
                return ResourceManager.GetString("Drill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drilling.
        /// </summary>
        public static string DrillingOp {
            get {
                return ResourceManager.GetString("DrillingOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drilling .
        /// </summary>
        public static string DrillingTool {
            get {
                return ResourceManager.GetString("DrillingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern.
        /// </summary>
        public static string Esterna {
            get {
                return ResourceManager.GetString("Esterna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extern.
        /// </summary>
        public static string Extern {
            get {
                return ResourceManager.GetString("Extern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Groove.
        /// </summary>
        public static string FaceGroove {
            get {
                return ResourceManager.GetString("FaceGroove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Mill.
        /// </summary>
        public static string FaceMill {
            get {
                return ResourceManager.GetString("FaceMill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Milling.
        /// </summary>
        public static string FaceMilling {
            get {
                return ResourceManager.GetString("FaceMilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face Turning.
        /// </summary>
        public static string FaceTurning {
            get {
                return ResourceManager.GetString("FaceTurning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        public static string Feed {
            get {
                return ResourceManager.GetString("Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixture.
        /// </summary>
        public static string Fixture {
            get {
                return ResourceManager.GetString("Fixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flat Mill.
        /// </summary>
        public static string FlatMill {
            get {
                return ResourceManager.GetString("FlatMill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grooving.
        /// </summary>
        public static string GroovingOp {
            get {
                return ResourceManager.GetString("GroovingOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hexagon.
        /// </summary>
        public static string Hexagon {
            get {
                return ResourceManager.GetString("Hexagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourly Cost.
        /// </summary>
        public static string HourlyCost {
            get {
                return ResourceManager.GetString("HourlyCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inch.
        /// </summary>
        public static string Inch {
            get {
                return ResourceManager.GetString("Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Profile.
        /// </summary>
        public static string InputProfile {
            get {
                return ResourceManager.GetString("InputProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intern.
        /// </summary>
        public static string Intern {
            get {
                return ResourceManager.GetString("Intern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intern.
        /// </summary>
        public static string Interna {
            get {
                return ResourceManager.GetString("Interna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting Width (ae).
        /// </summary>
        public static string LarghezzaPassata {
            get {
                return ResourceManager.GetString("LarghezzaPassata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lathe 2 Axis.
        /// </summary>
        public static string Lathe2Ax {
            get {
                return ResourceManager.GetString("Lathe2Ax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lathe 3 Axis.
        /// </summary>
        public static string Lathe3Ax {
            get {
                return ResourceManager.GetString("Lathe3Ax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Machine : [sec].
        /// </summary>
        public static string LoadingMachine {
            get {
                return ResourceManager.GetString("LoadingMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Machine.
        /// </summary>
        public static string LoadingMachineTv {
            get {
                return ResourceManager.GetString("LoadingMachineTv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name.
        /// </summary>
        public static string MachineName {
            get {
                return ResourceManager.GetString("MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machines.
        /// </summary>
        public static string MachinesDialog {
            get {
                return ResourceManager.GetString("MachinesDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Selected.
        /// </summary>
        public static string MachineSelected {
            get {
                return ResourceManager.GetString("MachineSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machining Time.
        /// </summary>
        public static string MachiningTime {
            get {
                return ResourceManager.GetString("MachiningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materials.
        /// </summary>
        public static string MaterialDialog {
            get {
                return ResourceManager.GetString("MaterialDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Group.
        /// </summary>
        public static string MaterialGroup {
            get {
                return ResourceManager.GetString("MaterialGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material Selected.
        /// </summary>
        public static string MaterialSelected {
            get {
                return ResourceManager.GetString("MaterialSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Rev.
        /// </summary>
        public static string MaxRev {
            get {
                return ResourceManager.GetString("MaxRev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mill.
        /// </summary>
        public static string Mill {
            get {
                return ResourceManager.GetString("Mill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Millimeter.
        /// </summary>
        public static string Millimeter {
            get {
                return ResourceManager.GetString("Millimeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milling Preference.
        /// </summary>
        public static string MillingPreference {
            get {
                return ResourceManager.GetString("MillingPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milling.
        /// </summary>
        public static string MillingTool {
            get {
                return ResourceManager.GetString("MillingTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        public static string MillThreadOp {
            get {
                return ResourceManager.GetString("MillThreadOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounting Tools.
        /// </summary>
        public static string MountingTools {
            get {
                return ResourceManager.GetString("MountingTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        public static string NewFile {
            get {
                return ResourceManager.GetString("NewFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Phase.
        /// </summary>
        public static string NewPhase {
            get {
                return ResourceManager.GetString("NewPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N° Passate.
        /// </summary>
        public static string NumberPassate {
            get {
                return ResourceManager.GetString("NumberPassate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenFile {
            get {
                return ResourceManager.GetString("OpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Slot.
        /// </summary>
        public static string OpenSlot {
            get {
                return ResourceManager.GetString("OpenSlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Param. Material .
        /// </summary>
        public static string ParamMaterial {
            get {
                return ResourceManager.GetString("ParamMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific gravity.
        /// </summary>
        public static string pesoSpecifico {
            get {
                return ResourceManager.GetString("pesoSpecifico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Description.
        /// </summary>
        public static string PhaseDescription {
            get {
                return ResourceManager.GetString("PhaseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Property.
        /// </summary>
        public static string PhaseProperty {
            get {
                return ResourceManager.GetString("PhaseProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pipe.
        /// </summary>
        public static string Pipe {
            get {
                return ResourceManager.GetString("Pipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pitch.
        /// </summary>
        public static string Pitch {
            get {
                return ResourceManager.GetString("Pitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plunge Feed.
        /// </summary>
        public static string PlungeFeed {
            get {
                return ResourceManager.GetString("PlungeFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocket.
        /// </summary>
        public static string PocketOp {
            get {
                return ResourceManager.GetString("PocketOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        public static string preference {
            get {
                return ResourceManager.GetString("preference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutting Depth (ap).
        /// </summary>
        public static string ProfonditaPassata {
            get {
                return ResourceManager.GetString("ProfonditaPassata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmation.
        /// </summary>
        public static string Programmation {
            get {
                return ResourceManager.GetString("Programmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming Operation : [min].
        /// </summary>
        public static string ProgrammingOperationTime {
            get {
                return ResourceManager.GetString("ProgrammingOperationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid Time.
        /// </summary>
        public static string RapidTime {
            get {
                return ResourceManager.GetString("RapidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid.
        /// </summary>
        public static string RapidVel {
            get {
                return ResourceManager.GetString("RapidVel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reamer.
        /// </summary>
        public static string Reamer {
            get {
                return ResourceManager.GetString("Reamer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reamering.
        /// </summary>
        public static string Reamering {
            get {
                return ResourceManager.GetString("Reamering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectangle.
        /// </summary>
        public static string Rectangle {
            get {
                return ResourceManager.GetString("Rectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rev\Min.
        /// </summary>
        public static string RevMin {
            get {
                return ResourceManager.GetString("RevMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveAs.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string ScreenBack {
            get {
                return ResourceManager.GetString("ScreenBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string ScreenForward {
            get {
                return ResourceManager.GetString("ScreenForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure Distance.
        /// </summary>
        public static string SecureDistance {
            get {
                return ResourceManager.GetString("SecureDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecureRapidFeed.
        /// </summary>
        public static string SecureRapidFeed {
            get {
                return ResourceManager.GetString("SecureRapidFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Fixture Time : [min].
        /// </summary>
        public static string SetupFixtureTime {
            get {
                return ResourceManager.GetString("SetupFixtureTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Fixture.
        /// </summary>
        public static string SetupFixtureTv {
            get {
                return ResourceManager.GetString("SetupFixtureTv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Machine.
        /// </summary>
        public static string SetupMachine {
            get {
                return ResourceManager.GetString("SetupMachine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Tool Time : [min].
        /// </summary>
        public static string SetupToolTime {
            get {
                return ResourceManager.GetString("SetupToolTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Side.
        /// </summary>
        public static string SideOp {
            get {
                return ResourceManager.GetString("SideOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleDrilling.
        /// </summary>
        public static string SimpleDrilling {
            get {
                return ResourceManager.GetString("SimpleDrilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot.
        /// </summary>
        public static string SlotOp {
            get {
                return ResourceManager.GetString("SlotOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Operation.
        /// </summary>
        public static string SortOperation {
            get {
                return ResourceManager.GetString("SortOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        public static string Square {
            get {
                return ResourceManager.GetString("Square", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Quantity.
        /// </summary>
        public static string StockQuantity {
            get {
                return ResourceManager.GetString("StockQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string Tabelle {
            get {
                return ResourceManager.GetString("Tabelle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string TableGroup {
            get {
                return ResourceManager.GetString("TableGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap.
        /// </summary>
        public static string Tap {
            get {
                return ResourceManager.GetString("Tap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap Drill.
        /// </summary>
        public static string TapDrill {
            get {
                return ResourceManager.GetString("TapDrill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tapping.
        /// </summary>
        public static string Tapping {
            get {
                return ResourceManager.GetString("Tapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThreadMill.
        /// </summary>
        public static string ThreadMill {
            get {
                return ResourceManager.GetString("ThreadMill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread Table.
        /// </summary>
        public static string ThreadTableDialog {
            get {
                return ResourceManager.GetString("ThreadTableDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Calculation Stuff.
        /// </summary>
        public static string TimeCalculationGroup {
            get {
                return ResourceManager.GetString("TimeCalculationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Change.
        /// </summary>
        public static string ToolChange {
            get {
                return ResourceManager.GetString("ToolChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Change Time.
        /// </summary>
        public static string ToolChangeTv {
            get {
                return ResourceManager.GetString("ToolChangeTv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Cost.
        /// </summary>
        public static string ToolCost {
            get {
                return ResourceManager.GetString("ToolCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Detail.
        /// </summary>
        public static string toolDetailGroup {
            get {
                return ResourceManager.GetString("toolDetailGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string ToolDialog {
            get {
                return ResourceManager.GetString("ToolDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Label.
        /// </summary>
        public static string ToolLabel {
            get {
                return ResourceManager.GetString("ToolLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifespan.
        /// </summary>
        public static string ToolLifeTimeSpan {
            get {
                return ResourceManager.GetString("ToolLifeTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool Wear.
        /// </summary>
        public static string ToolWear {
            get {
                return ResourceManager.GetString("ToolWear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning.
        /// </summary>
        public static string Tornitura {
            get {
                return ResourceManager.GetString("Tornitura", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groove.
        /// </summary>
        public static string TurnGroove {
            get {
                return ResourceManager.GetString("TurnGroove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning.
        /// </summary>
        public static string TurningOp {
            get {
                return ResourceManager.GetString("TurningOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning Preference.
        /// </summary>
        public static string TurningPreference {
            get {
                return ResourceManager.GetString("TurningPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turning.
        /// </summary>
        public static string TurningTool {
            get {
                return ResourceManager.GetString("TurningTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thread.
        /// </summary>
        public static string TurnThread {
            get {
                return ResourceManager.GetString("TurnThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threading.
        /// </summary>
        public static string TurnThreadingOp {
            get {
                return ResourceManager.GetString("TurnThreadingOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Tool.
        /// </summary>
        public static string TurnTool {
            get {
                return ResourceManager.GetString("TurnTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Preview.
        /// </summary>
        public static string UpdatePreview {
            get {
                return ResourceManager.GetString("UpdatePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VariousCost.
        /// </summary>
        public static string VariousCost {
            get {
                return ResourceManager.GetString("VariousCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical Mill.
        /// </summary>
        public static string VerticalMill {
            get {
                return ResourceManager.GetString("VerticalMill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        public static string Voce {
            get {
                return ResourceManager.GetString("Voce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string WorkCycle {
            get {
                return ResourceManager.GetString("WorkCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        public static string WorkParameter {
            get {
                return ResourceManager.GetString("WorkParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Time.
        /// </summary>
        public static string WorkTime {
            get {
                return ResourceManager.GetString("WorkTime", resourceCulture);
            }
        }
    }
}
