//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CncConvProg.View.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LicenseInfo", Namespace="http://schemas.datacontract.org/2004/07/MecprevService")]
    [System.SerializableAttribute()]
    public partial class LicenseInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndLicenseTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncorrectKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LicenseValidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndLicenseTime {
            get {
                return this.EndLicenseTimeField;
            }
            set {
                if ((this.EndLicenseTimeField.Equals(value) != true)) {
                    this.EndLicenseTimeField = value;
                    this.RaisePropertyChanged("EndLicenseTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncorrectKey {
            get {
                return this.IncorrectKeyField;
            }
            set {
                if ((this.IncorrectKeyField.Equals(value) != true)) {
                    this.IncorrectKeyField = value;
                    this.RaisePropertyChanged("IncorrectKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LicenseValid {
            get {
                return this.LicenseValidField;
            }
            set {
                if ((this.LicenseValidField.Equals(value) != true)) {
                    this.LicenseValidField = value;
                    this.RaisePropertyChanged("LicenseValid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLicenseInfo", ReplyAction="http://tempuri.org/IService1/GetLicenseInfoResponse")]
        CncConvProg.View.ServiceReference1.LicenseInfo GetLicenseInfo(string licenseKey, string macId, System.DateTime endPreviousLicense);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Rep", ReplyAction="http://tempuri.org/IService1/RepResponse")]
        void Rep(double min, string mi, string e, string l);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : CncConvProg.View.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<CncConvProg.View.ServiceReference1.IService1>, CncConvProg.View.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CncConvProg.View.ServiceReference1.LicenseInfo GetLicenseInfo(string licenseKey, string macId, System.DateTime endPreviousLicense) {
            return base.Channel.GetLicenseInfo(licenseKey, macId, endPreviousLicense);
        }
        
        public void Rep(double min, string mi, string e, string l) {
            base.Channel.Rep(min, mi, e, l);
        }
    }
}
